[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor & Upload Settings
monitor_speed = 115200
upload_speed = 921600

; Automatically download and include FastLED library
lib_deps = 
    fastled/FastLED @ ^3.6.0